import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getService, services } from "@/lib/services";
import { VehicleContextBar } from "@/components/VehicleContextBar";
import { ServiceAiAssist } from "@/components/ServiceAiAssist";

export function generateStaticParams(){return services.map((service)=>({service:service.slug}));}
export async function generateMetadata({params}:{params:Promise<{service:string}>}):Promise<Metadata>{const {service}=await params;const item=getService(service);return item?{title:item.name,description:`${item.name} на TURBO LEV: AI + номер/VIN-контекст, діагностика, підбір деталей і встановлення.`}:{};}
export default async function ServicePage({params}:{params:Promise<{service:string}>}){const {service}=await params;const item=getService(service);if(!item)notFound();return <div className="shell page section service-detail"><div className="breadcrumbs"><Link href="/">Головна</Link><span>›</span><Link href="/poslugy">Послуги</Link><span>›</span><span>{item.name}</span></div><div className="service-detail-hero"><div><span className="kicker">TURBO LEV · {item.icon}</span><h1>{item.name.toUpperCase()}</h1><p className="lead">{item.short}</p><div className="service-actions"><Link className="button button-accent" href={`/zapys?service=${item.slug}`}>ЗАПИСАТИСЯ НА СТО</Link>{item.relatedCategory?<Link className="button button-dark" href={`/zapchastyny/${item.relatedCategory}`}>ПІДІБРАТИ ДЕТАЛІ</Link>:null}</div></div><div className="service-number">SERVICE<br/><b>{item.icon}</b></div></div><VehicleContextBar/><ServiceAiAssist serviceName={item.name}/><div className="service-columns"><section><span className="kicker">КОЛИ ЗВЕРТАТИСЯ</span><h2>ТИПОВІ СИМПТОМИ</h2><ul>{item.symptoms.map((x)=><li key={x}>{x}</li>)}</ul></section><section><span className="kicker">ЩО РОБИМО</span><h2>МАРШРУТ РОБОТИ</h2><ol>{item.scope.map((x,i)=><li key={x}><b>{String(i+1).padStart(2,"0")}</b><span>{x}</span></li>)}</ol></section></div><section className="service-truth"><strong>ВАЖЛИВО</strong><p>Симптом ≠ діагноз. TURBO LEV AI може звузити сценарій і підготувати контекст, але остаточна рекомендація по ремонту та деталях формується після перевірки даних і, коли потрібно, фізичної діагностики автомобіля.</p></section></div>}
