import type { Metadata } from "next";
import Link from "next/link";
import { money, products } from "@/lib/catalog";
import { CartVehicleGate } from "@/components/CartVehicleGate";
import { VehicleContextBar } from "@/components/VehicleContextBar";
import { VehicleIdentityResolver } from "@/components/VehicleIdentityResolver";

export const metadata: Metadata = { title: "Кошик", robots: { index: false, follow: false } };
const item = products[0];
export default function CartPage(){return <div className="shell page section cart-page"><div className="breadcrumbs"><Link href="/">Головна</Link><span>›</span><span>Кошик</span></div><div className="cart-head"><div><span className="kicker">TURBO LEV · CHECKOUT</span><h1>КОШИК</h1><p>Перед створенням замовлення ще раз перевіримо автомобіль, сумісність, ціну й наявність.</p></div><span className="cart-step">01 / 03</span></div><VehicleContextBar/><VehicleIdentityResolver compact title="АВТО ДЛЯ ЦЬОГО КОШИКА" purpose="SHOP"/><CartVehicleGate/><div className="cart-layout"><div className="cart-lines"><article className="cart-line"><div className="cart-product-mark"><b>{item.brand}</b><span>{item.article}</span></div><div className="cart-line-info"><span className="eyebrow">{item.brand} · {item.article}</span><h2>{item.name}</h2><p className="stock ok-dot">{item.availability}</p><div className="cart-line-meta"><span>Кількість: 1</span><span>Fitment: НЕ ПІДТВЕРДЖЕНО</span><Link href={`/zapchastyny/${item.category}/${item.slug}`}>Картка товару</Link></div></div><strong className="cart-line-price">{money(item.price)}</strong></article><section className="cart-install"><div><span>ДЕТАЛЬ + ВСТАНОВЛЕННЯ</span><strong>Додати роботу TURBO LEV?</strong><p>Vehicle context і товар будуть передані у booking handoff без raw VIN/держномера в analytics.</p></div><Link href={`/zapys?intent=install&product=${encodeURIComponent(item.article)}`}>ДОДАТИ ВСТАНОВЛЕННЯ →</Link></section></div><aside className="cart-summary"><span>ПІДСУМОК</span><div><p>Товари <b>{money(item.price)}</b></p><p>Доставка <b>після вибору способу</b></p><p>Встановлення <b>не додано</b></p></div><hr/><p className="cart-total">До оплати <strong>{money(item.price)}</strong></p><Link className="button button-accent" href="/oformlennia">ПЕРЕВІРИТИ Й ПРОДОВЖИТИ</Link><small>Production: product fitment → price/stock revalidate → quote → reserve → durable order.</small></aside></div></div>}
