export type Service = { slug:string; name:string; short:string; symptoms:string[]; scope:string[]; relatedCategory?:string; icon:string };
export const services:Service[]=[
{slug:"diagnostyka-hodovoi",name:"Діагностика ходової",short:"Перевірка підвіски та кермового керування перед ремонтом.",symptoms:["Стук на нерівностях","Люфт керма","Нерівномірний знос шин"],scope:["Огляд підвіски","Перевірка люфтів","Формування списку робіт"],relatedCategory:"pidviska",icon:"◇"},
{slug:"zamina-halmivnyh-kolodok",name:"Заміна гальмівних колодок",short:"Перевірка гальмівної системи та заміна колодок із контролем сумісності.",symptoms:["Скрип або писк","Вібрація при гальмуванні","Збільшений гальмівний шлях"],scope:["Огляд дисків і супортів","Fitment деталей","Заміна колодок"],relatedCategory:"halmivna-systema",icon:"◉"},
{slug:"zamina-amortyzatoriv",name:"Заміна амортизаторів",short:"Діагностика та заміна амортизаторів із перевіркою опор і пружин.",symptoms:["Розгойдування кузова","Стук","Підтікання"],scope:["Огляд стійки","Підбір деталей","Заміна і контроль"],relatedCategory:"pidviska",icon:"↕"},
{slug:"remont-kermovoi-reiky",name:"Ремонт кермової рейки",short:"Діагностика люфтів, підтікань і допоміжних систем кермового керування.",symptoms:["Стук у кермі","Підтікання рідини","Туге кермо"],scope:["Діагностика рейки","Перевірка ГПК","Підбір і монтаж деталей"],relatedCategory:"keruvannia",icon:"◎"},
{slug:"kompiuterna-diagnostyka",name:"Комп’ютерна діагностика",short:"Зчитування помилок і параметрів як старт для пошуку несправності, а не заміна реальної діагностики.",symptoms:["Check Engine","Помилки систем","Нестабільна робота двигуна"],scope:["Зчитування DTC","Live data","Рекомендація наступного кроку"],relatedCategory:"elektryka",icon:"AI"},
{slug:"zapchastyna-vstanovlennia",name:"Запчастина + встановлення",short:"Один сценарій: підбір сумісної деталі, замовлення та встановлення на TURBO LEV.",symptoms:["Є артикул, але не впевнені у сумісності","Потрібна деталь і майстер"],scope:["Vehicle/VIN контекст","Fitment-перевірка","Вибір пропозиції","Передача товару в запис на СТО"],icon:"TL"}
];
export function getService(slug:string){return services.find(s=>s.slug===slug)??null}
